# .github/workflows/ci.yml

name: CI

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2

    - name: Install dependencies
      run: |
        pip config unset global.index-url
        pip config unset global.trusted-host
        pip install -r requirements.txt

    - name: Run flake8
      run: make flake8

    - name: Run yapf
      run: make py-format

  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2

    - name: Install dependencies
      run: |
        pip config unset global.index-url
        pip config unset global.trusted-host
        pip install -r requirements.txt

    - name: Run tests
      run: bazel test --test_output=all //tests/...
